Repository CodersCrew/coderscamp, pull requests merged in 2021-09, with the labels that each got.

#264 fix: change text in section "Czym jest CodersCamp" (#253)
  packages/website/src/components/About.tsx
Labels: ⏱ 1 minute PR

#268 fix(website): add error handling for supabase call in recruitment-form
  packages/website/src/pages/api/recruitment-form.ts
Labels: ⏱ 1 minute PR

#302 refactor: rename custom validators to be UpperCamelCase
  packages/shared/src/models/course.ts
  packages/shared/src/types.ts
  packages/shared/src/utils/validators.ts
Labels: ⏱ 1 minute PR

#233 fix: bigger buttons on the mobile site (#205)
  packages/website/src/components/Hero.tsx
  packages/website/src/components/Navbar/BaseNavbar.tsx
  packages/website/src/components/Navbar/Navbar.tsx
Labels: ⏱ 1 minute PR

#308 feat(api): [emailConfirmation] create event type EmailConfirmationWasApproved #285
  packages/api/src/module/shared/events/email-confirmation-was-approved.domain.event.ts
Labels: ⏱ 1 minute PR

#306 fix(website): fix navbar logo sizing and mentor testimonial spacing
  packages/website/src/components/Navbar/BaseNavbar.tsx
  packages/website/src/components/Testimonials/MentorTestimonials/MentorTestimonialCard.tsx
Labels: ⏱ 1 minute PR

#301 refactor(shared): remove unused utils files
  .github/workflows/pull-request.yml
  packages/shared/src/utils/lang.ts
  packages/shared/src/utils/test.ts
Labels: ⏱ 1 minute PR

#339 feat(website): logo is not displayed in Navbar [Safari] #334
  packages/website/src/components/Footer/Footer.data.tsx
  packages/website/src/components/Navbar/BaseNavbar.tsx
  packages/website/src/components/Navbar/Navbar.tsx
  packages/website/src/constants.ts
Labels: 🦄 for design review

#240 fix(website): bigger dots in horizontal nav (#206)
  packages/ui/src/components/IconButton/IconButton.tsx
  packages/ui/src/components/SliderSteps/SliderStep.tsx
  packages/ui/src/components/SliderSteps/SliderSteps.test.tsx
  packages/ui/src/components/SliderSteps/SliderSteps.tsx
  packages/ui/src/hooks/useCurrentBreakpoint.ts
  packages/ui/src/types.ts
  packages/website/src/components/Testimonials/TestimonialsCarousel.tsx
Labels: ⏱ 1 minute PR, 🦄 for design review

#349 feat(api): dotenv config for tests (#348)
  .github/workflows/code-check.yml
  packages/api/.env.test
  packages/api/jest-setup.ts
Labels: ⏱ 1 minute PR

#351 feat(api): configurable retries for EventsSubscription #350
  packages/api/jest-setup.ts
  packages/api/src/module/write/shared/application/events-subscription/events-subscription-builder.ts
  packages/api/src/module/write/shared/application/events-subscription/events-subscription.spec.ts
  packages/api/src/module/write/shared/application/events-subscription/events-subscription.ts
  packages/api/src/module/write/shared/application/events-subscription/events-subscriptions-registry.ts
Labels: ⏱ 1 minute PR

#340 feat(api): create slice SendEmailMessage -> EmailMessageWasSent (#261)
  packages/api/.env.example
  packages/api/.env.test
  packages/api/package.json
  packages/api/src/module/shared/commands/send-email-message.application-command.ts
  packages/api/src/module/shared/commands/send-email-message.domain-command.ts
  packages/api/src/module/shared/events/email-message-was-sent.domain-event.ts
  packages/api/src/module/write/email-sender/application/email-sender.ts
  packages/api/src/module/write/email-sender/application/send-email-message.command-handler.ts
  packages/api/src/module/write/email-sender/domain/events.ts
  packages/api/src/module/write/email-sender/domain/sendEmailMessage.spec.ts
  packages/api/src/module/write/email-sender/domain/sendEmailMessage.ts
  packages/api/src/module/write/email-sender/email-sending.spec.ts
  packages/api/src/module/write/email-sender/email-sending.test-module.ts
  packages/api/src/module/write/email-sender/email-sending.write-module.ts
  packages/api/src/module/write/email-sender/infrastructure/just-log.email-sender.ts
  packages/api/src/module/write/email-sender/infrastructure/node-mailer-email-sender.ts
  packages/api/src/shared/domain.types.ts
  packages/api/src/shared/env.ts
  yarn.lock
Labels: type: ✨ feat
